/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5_franciscopagoaga;

import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Francisco Pagoaga
 */
public class Visual extends javax.swing.JFrame {

    /**
     * Creates new form Visual
     */
    public Visual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Estudiantes = new javax.swing.JDialog();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nombreestud = new javax.swing.JTextField();
        apellidoestud = new javax.swing.JTextField();
        numcuenta = new javax.swing.JFormattedTextField();
        edadestud = new javax.swing.JFormattedTextField();
        masculino = new javax.swing.JRadioButton();
        femenino = new javax.swing.JRadioButton();
        cb1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        carreras = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jefecarrera = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        mensualidad = new javax.swing.JTextField();
        Clase = new javax.swing.JDialog();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Conaire = new javax.swing.JRadioButton();
        sinaire = new javax.swing.JRadioButton();
        jLabel18 = new javax.swing.JLabel();
        Seccion = new javax.swing.JTextField();
        Edificio = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Salon = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        nombclase = new javax.swing.JTextField();
        Maestros = new javax.swing.JDialog();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        nombmaestro = new javax.swing.JTextField();
        apellidomaestro = new javax.swing.JTextField();
        paga = new javax.swing.JTextField();
        Edad = new javax.swing.JFormattedTextField();
        agregrarmaestro = new javax.swing.JButton();
        genero = new javax.swing.ButtonGroup();
        tree = new javax.swing.JPopupMenu();
        Eliminar = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        Aire = new javax.swing.ButtonGroup();
        Listas = new javax.swing.JPopupMenu();
        Modificar = new javax.swing.JMenuItem();
        agregarestudiantes = new javax.swing.JButton();
        agregarclases = new javax.swing.JButton();
        agregarmaestros = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaestud = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        treeestud = new javax.swing.JTree();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listamaestros = new javax.swing.JList<>();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listaclases = new javax.swing.JList<>();

        jLabel4.setText("Nombre:");

        jLabel5.setText("Apellido:");

        jLabel6.setText("Numero de Cuenta:");

        jLabel7.setText("Edad");

        jLabel8.setText("Genero");

        nombreestud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreestudActionPerformed(evt);
            }
        });

        try {
            numcuenta.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            edadestud.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        genero.add(masculino);
        masculino.setText("M");

        genero.add(femenino);
        femenino.setText("F");

        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Licenciatura", "Ingenieria", "Ciencias de la Salud", " " }));
        cb1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb1ItemStateChanged(evt);
            }
        });

        jLabel9.setText("Carrera");

        carreras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Finanzas", "Derecho", "Administracion de Emprezas", "Diseño Grafico", "Mercadotecnia", " " }));

        jButton1.setText("Agregar Estudiante");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel1.setText("Jefe de Carrera:");

        jLabel2.setText("Costo Mensual:");

        javax.swing.GroupLayout EstudiantesLayout = new javax.swing.GroupLayout(Estudiantes.getContentPane());
        Estudiantes.getContentPane().setLayout(EstudiantesLayout);
        EstudiantesLayout.setHorizontalGroup(
            EstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EstudiantesLayout.createSequentialGroup()
                .addGroup(EstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EstudiantesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(EstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EstudiantesLayout.createSequentialGroup()
                                .addGroup(EstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, EstudiantesLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nombreestud))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, EstudiantesLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(apellidoestud, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(EstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(EstudiantesLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jefecarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(EstudiantesLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(mensualidad))))
                            .addGroup(EstudiantesLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(edadestud, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(EstudiantesLayout.createSequentialGroup()
                                .addGroup(EstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(EstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(EstudiantesLayout.createSequentialGroup()
                                        .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(carreras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(EstudiantesLayout.createSequentialGroup()
                                        .addComponent(masculino)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(femenino))))
                            .addGroup(EstudiantesLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numcuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(EstudiantesLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        EstudiantesLayout.setVerticalGroup(
            EstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EstudiantesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nombreestud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jefecarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(apellidoestud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(mensualidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(numcuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(edadestud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(masculino)
                    .addComponent(femenino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(EstudiantesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(carreras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jLabel16.setText("Nombre");

        jLabel17.setText("Aire Acondicionado");

        Aire.add(Conaire);
        Conaire.setText("Con Aire");

        Aire.add(sinaire);
        sinaire.setText("Sin aire");

        jLabel18.setText("seccion");

        jLabel19.setText("Edificio");

        jLabel20.setText("Salon");

        jButton2.setText("Agregar Clase");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout ClaseLayout = new javax.swing.GroupLayout(Clase.getContentPane());
        Clase.getContentPane().setLayout(ClaseLayout);
        ClaseLayout.setHorizontalGroup(
            ClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClaseLayout.createSequentialGroup()
                .addGroup(ClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ClaseLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ClaseLayout.createSequentialGroup()
                                .addGroup(ClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(ClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Edificio)
                                    .addComponent(Seccion)))
                            .addGroup(ClaseLayout.createSequentialGroup()
                                .addGroup(ClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(ClaseLayout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Conaire)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(sinaire))
                                    .addGroup(ClaseLayout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nombclase))
                                    .addGroup(ClaseLayout.createSequentialGroup()
                                        .addComponent(jLabel20)
                                        .addGap(22, 22, 22)
                                        .addComponent(Salon)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(ClaseLayout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(jButton2)))
                .addGap(117, 117, 117))
        );
        ClaseLayout.setVerticalGroup(
            ClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClaseLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(nombclase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(sinaire)
                    .addComponent(Conaire))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(Seccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Edificio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ClaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(Salon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(80, 80, 80))
        );

        jLabel12.setText("Nombre");

        jLabel13.setText("Apellido");

        jLabel14.setText("Salario");

        jLabel15.setText("Edad");

        try {
            Edad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        agregrarmaestro.setText("Agregar");
        agregrarmaestro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregrarmaestroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout MaestrosLayout = new javax.swing.GroupLayout(Maestros.getContentPane());
        Maestros.getContentPane().setLayout(MaestrosLayout);
        MaestrosLayout.setHorizontalGroup(
            MaestrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MaestrosLayout.createSequentialGroup()
                .addGroup(MaestrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MaestrosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(MaestrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MaestrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(MaestrosLayout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(nombmaestro, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(MaestrosLayout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(apellidomaestro))
                                .addGroup(MaestrosLayout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addGap(18, 18, 18)
                                    .addComponent(paga, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(MaestrosLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(30, 30, 30)
                                .addComponent(Edad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(MaestrosLayout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addComponent(agregrarmaestro)))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        MaestrosLayout.setVerticalGroup(
            MaestrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MaestrosLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(MaestrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(nombmaestro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MaestrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(apellidomaestro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MaestrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(paga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(MaestrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(Edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(agregrarmaestro)
                .addGap(89, 89, 89))
        );

        Eliminar.setText("jMenuItem1");
        tree.add(Eliminar);

        jMenuItem1.setText("jMenuItem1");
        tree.add(jMenuItem1);

        Modificar.setText("Eliminar");
        Listas.add(Modificar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        agregarestudiantes.setText("Agregar Estudiantes");
        agregarestudiantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarestudiantesMouseClicked(evt);
            }
        });

        agregarclases.setText("Agregar Clases");
        agregarclases.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarclasesMouseClicked(evt);
            }
        });

        agregarmaestros.setText("Agregar Mestros");
        agregarmaestros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarmaestrosMouseClicked(evt);
            }
        });

        jLabel3.setText("Estudiantes");

        listaestud.setModel(new DefaultListModel());
        listaestud.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaestudMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listaestud);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Carreras");
        treeestud.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane3.setViewportView(treeestud);

        jLabel10.setText("Maestros");

        listamaestros.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(listamaestros);

        jLabel11.setText("Clases");

        listaclases.setModel(new DefaultListModel());
        jScrollPane4.setViewportView(listaclases);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(agregarestudiantes)
                        .addGap(318, 318, 318)
                        .addComponent(agregarclases)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(85, 133, Short.MAX_VALUE)))
                        .addGap(243, 243, 243)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(167, 167, 167))))
            .addGroup(layout.createSequentialGroup()
                .addGap(413, 413, 413)
                .addComponent(agregarmaestros)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarclases)
                    .addComponent(agregarestudiantes))
                .addGap(46, 46, 46)
                .addComponent(agregarmaestros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane4)
                    .addComponent(jScrollPane1))
                .addContainerGap(170, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nombreestudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreestudActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreestudActionPerformed

    private void cb1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb1ItemStateChanged
        // TODO add your handling code here:
        if (cb1.getSelectedIndex() == 0) {
            carreras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Finanzas", "Derecho", "Administracion de Emprezas", "Diseño Grafico", "Mercadotecnia"}));
        } else if (cb1.getSelectedIndex() == 1) {
            carreras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Sistemas Computacionales", "Industrial y de Sistemas", "Mecatrónica", "Biomédica", "Energía"}));
        } else if (cb1.getSelectedIndex() == 2) {
            carreras.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Sistemas Computacionales", "Industrial y de Sistemas", "Mecatrónica", "Biomédica", "Energía"}));
        }
    }//GEN-LAST:event_cb1ItemStateChanged

    private void agregarestudiantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarestudiantesMouseClicked
        // TODO add your handling code here:
        Estudiantes.setModal(true);
        Estudiantes.pack();
        Estudiantes.setLocationRelativeTo(this);
        Estudiantes.setVisible(true);
    }//GEN-LAST:event_agregarestudiantesMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        try {
            String genero = "";
            String nombre = nombreestud.getText();
            String apellido = apellidoestud.getText();
            int numdecuenta = Integer.parseInt(numcuenta.getText());
            System.out.println(Integer.parseInt(numcuenta.getText()));
            int edad = Integer.parseInt(edadestud.getText());
            if (masculino.isSelected()) {
                genero = "Masuclino";
            } else if (femenino.isSelected()) {
                genero = "Femenino";
            }
            String facultad = (String) cb1.getSelectedItem();
            String carrera = (String) carreras.getSelectedItem();
            String jefedecarrera = jefecarrera.getText();
            double costomensual = Double.parseDouble(mensualidad.getText());
            DefaultListModel modelo = (DefaultListModel) listaestud.getModel();
            Carrera x = new Carrera(carrera, facultad, costomensual, jefedecarrera);
            modelo.addElement(new Estudiante(nombre, apellido, genero, numdecuenta, edad, x));
            listaestud.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(Estudiantes, "Sucedio un error y no se guardo");
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void listaestudMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaestudMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {

            if (listaestud.getSelectedIndex() >= 0) {
                DefaultTreeModel modeloARBOL = (DefaultTreeModel) treeestud.getModel();
                DefaultMutableTreeNode raiz = (DefaultMutableTreeNode) modeloARBOL.getRoot();
                //obtener la persona a guardar
                DefaultListModel modeloLISTA = (DefaultListModel) listaestud.getModel();
                String carrera, nombre, apellido, genero, facultad;
                int edad, numcuenta;
                Carrera x = ((Estudiante) modeloLISTA.get(listaestud.getSelectedIndex())).getCarrera();
                carrera = x.getNombre();
                facultad = x.getFacultad();
                nombre = ((Estudiante) modeloLISTA.get(listaestud.getSelectedIndex())).getNombre();
                apellido = ((Estudiante) modeloLISTA.get(listaestud.getSelectedIndex())).getApellido();
                genero = ((Estudiante) modeloLISTA.get(listaestud.getSelectedIndex())).getGenero();
                numcuenta = ((Estudiante) modeloLISTA.get(listaestud.getSelectedIndex())).getNumcuenta();
                edad = ((Estudiante) modeloLISTA.get(listaestud.getSelectedIndex())).getEdad();
                int centinela = -1;
                int centinela2 = -1,centinela3=-1;
                for (int i = 0; i < raiz.getChildCount(); i++) {
                    if (raiz.getChildAt(i).toString().equals(facultad)) {
                        for (int j = 0; j < raiz.getChildAt(i).getChildCount(); j++) {
                            if (raiz.getChildAt(i).getChildAt(j).toString().equals(carrera)) {
                                for (int k = 0; k < raiz.getChildAt(i).getChildAt(j).getChildCount(); k++) {
                                    if (raiz.getChildAt(i).getChildAt(j).getChildAt(k).toString().equals("Estudiantes")) {
                                        DefaultMutableTreeNode p = new DefaultMutableTreeNode(new Estudiante(nombre, apellido, genero, numcuenta, edad, x));
                                        ((DefaultMutableTreeNode)raiz.getChildAt(i).getChildAt(j).getChildAt(k)).add(p);
                                    }
                                    centinela3=1;
                                }
                                centinela=1;
                            }
                        }
                        centinela2 = 1;
                    } 
                }
                if (centinela2 == -1) {
                    DefaultMutableTreeNode n = new DefaultMutableTreeNode(facultad);
                    raiz.add(n);
                    raiz.getIndex(n);
                    DefaultMutableTreeNode q=new DefaultMutableTreeNode(carrera);
                    ((DefaultMutableTreeNode)raiz.getChildAt(raiz.getIndex(n))).add(q);
                    DefaultMutableTreeNode t=new DefaultMutableTreeNode("Estudiantes");
                    ((DefaultMutableTreeNode)raiz.getChildAt(raiz.getIndex(n)).getChildAt(0)).add(t);
                    DefaultMutableTreeNode p = new DefaultMutableTreeNode(new Estudiante(nombre, apellido, genero, numcuenta, edad, x));
                    ((DefaultMutableTreeNode)raiz.getChildAt(raiz.getIndex(n)).getChildAt(0).getChildAt(0)).add(p);
                } else if (centinela==-1) {
                    DefaultMutableTreeNode q=new DefaultMutableTreeNode(carrera);
                    for (int i = 0; i < raiz.getChildCount(); i++) {
                        if (raiz.getChildAt(i).toString().equals(facultad)) {
                            ((DefaultMutableTreeNode)raiz.getChildAt(i)).add(q);
                            DefaultMutableTreeNode t=new DefaultMutableTreeNode("Estudiantes");
                            ((DefaultMutableTreeNode)raiz.getChildAt(i).getChildAt(0)).add(t);
                            DefaultMutableTreeNode p = new DefaultMutableTreeNode(new Estudiante(nombre, apellido, genero, numcuenta, edad, x));
                            ((DefaultMutableTreeNode)raiz.getChildAt(i).getChildAt(0).getChildAt(0)).add(p);
                            
                        }
                    }
                }
                modeloARBOL.reload();

            } else {
                JOptionPane.showMessageDialog(this,
                        "No hay persona seleccionada");
            }
        }
    }//GEN-LAST:event_listaestudMouseClicked

    private void agregrarmaestroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregrarmaestroMouseClicked
        // TODO add your handling code here:
        try {
            String nombre, apellido;
            int edad;
            double salario;
            nombre = nombmaestro.getText();
            apellido = apellidomaestro.getText();
            salario = Double.parseDouble(paga.getText());
            edad = Integer.parseInt(Edad.getText());
            DefaultListModel modelo = (DefaultListModel) listamaestros.getModel();
            modelo.addElement(new Maestros(nombre, apellido, salario, edad));
            listamaestros.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(Estudiantes, "Sucedio un error y no se guardo");
        }

    }//GEN-LAST:event_agregrarmaestroMouseClicked

    private void agregarmaestrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarmaestrosMouseClicked
        // TODO add your handling code here:
        Maestros.setModal(true);
        Maestros.pack();
        Maestros.setLocationRelativeTo(this);
        Maestros.setVisible(true);
    }//GEN-LAST:event_agregarmaestrosMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        try{
            String nombre, aire = "";
            int seccion, edificio, salon;
            nombre = nombclase.getText();
            if (Conaire.isSelected()) {
                aire = "Con aire";
            } else if (sinaire.isSelected()) {
                aire = "Sin aire";
            }
            seccion = Integer.parseInt(Seccion.getText());
            edificio = Integer.parseInt(Edificio.getText());
            salon = Integer.parseInt(Salon.getText());
            DefaultListModel modelo = (DefaultListModel) listaclases.getModel();
            modelo.addElement(new Clases(nombre,aire,seccion,edificio,salon));
            listaclases.setModel(modelo);
        } catch (Exception e){
            JOptionPane.showMessageDialog(Estudiantes, "Sucedio un error y no se guardo");
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void agregarclasesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarclasesMouseClicked
        // TODO add your handling code here:
        Clase.setModal(true);
        Clase.pack();
        Clase.setLocationRelativeTo(this);
        Clase.setVisible(true);
    }//GEN-LAST:event_agregarclasesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Visual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Aire;
    private javax.swing.JDialog Clase;
    private javax.swing.JRadioButton Conaire;
    private javax.swing.JFormattedTextField Edad;
    private javax.swing.JTextField Edificio;
    private javax.swing.JMenuItem Eliminar;
    private javax.swing.JDialog Estudiantes;
    private javax.swing.JPopupMenu Listas;
    private javax.swing.JDialog Maestros;
    private javax.swing.JMenuItem Modificar;
    private javax.swing.JTextField Salon;
    private javax.swing.JTextField Seccion;
    private javax.swing.JButton agregarclases;
    private javax.swing.JButton agregarestudiantes;
    private javax.swing.JButton agregarmaestros;
    private javax.swing.JButton agregrarmaestro;
    private javax.swing.JTextField apellidoestud;
    private javax.swing.JTextField apellidomaestro;
    private javax.swing.JComboBox<String> carreras;
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JFormattedTextField edadestud;
    private javax.swing.JRadioButton femenino;
    private javax.swing.ButtonGroup genero;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jefecarrera;
    private javax.swing.JList<String> listaclases;
    private javax.swing.JList<String> listaestud;
    private javax.swing.JList<String> listamaestros;
    private javax.swing.JRadioButton masculino;
    private javax.swing.JTextField mensualidad;
    private javax.swing.JTextField nombclase;
    private javax.swing.JTextField nombmaestro;
    private javax.swing.JTextField nombreestud;
    private javax.swing.JFormattedTextField numcuenta;
    private javax.swing.JTextField paga;
    private javax.swing.JRadioButton sinaire;
    private javax.swing.JPopupMenu tree;
    private javax.swing.JTree treeestud;
    // End of variables declaration//GEN-END:variables
}
